# Copyright 2018 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
#
# Playbook to test Segment
#
- hosts: localhost
  become: yes
  tasks:
    - name: Update Segment
      nsxt_segment:
        hostname: "default"
        username: "default"
        password: "default"
        validate_certs: False
        display_name: test-seg
        state: "present"
        tier1_display_name: "test-tier11"
        domain_name: "dn1"
        transport_zone_display_name: "1-transportzone-184"
        subnets:
        - gateway_address: "40.1.1.1/16"
        segp_display_name: "test-sp"
        segp_state: "present"