# Copyright 2018 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
#
# Playbook to test Segment
#
- hosts: localhost
  become: yes
  tasks:
    - name: Update Tier1
      nsxt_tier1:
        hostname: "default"
        username: "default"
        password: "default"
        validate_certs: False
        display_name: test-tier11
        state: "present"
        failover_mode: "PREEMPTIVE"
        disable_firewall: True
        force_whitelisting: True
        tags:
          - scope: "a"
            tag: "b"
        route_advertisement_rules:
          - name: "test-route-advertisement-rules"
            route_advertisement_types: ['TIER1_STATIC_ROUTES', 'TIER1_CONNECTED']
            subnets: ["35.1.1.1/23"]
        route_advertisement_types: ['TIER1_STATIC_ROUTES', 'TIER1_CONNECTED', 'TIER1_NAT']
        tier0_display_name: "test-tier00"
        t1ls_state: "present"
        t1ls_display_name: "test-t1ls"
        t1ls_route_redistribution_types: ["TIER0_STATIC", "TIER0_NAT"]
        t1iface_id: "test-t1-t1ls-iface"
        t1iface_display_name: "test-t1-t1ls-iface"
        t1iface_state: "present"
        t1iface_subnets:
          - ip_addresses: ["35.1.1.1"]
            prefix_len: 24
        t1iface_segment_id: "sg-uplink"