# Copyright 2018 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
#
# Playbook to test Segment
#
- hosts: localhost
  become: yes
  tasks:
    - name: create Policy Group
      nsxt_policy_group:
        hostname: "default"
        username: "default"
        password: "default"
        validate_certs: False
        id: test-policy-group
        display_name: test-policy-group
        state: "present"
        domain_id: "default"
        expression:
          - member_type: "VirtualMachine"
            value: "webvm"
            key: "Tag"
            operator: "EQUALS"
            resource_type: "Condition"